// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kelolakeuangan.Data;

namespace kelolakeuangan.Data.Migrations
{
    [DbContext(typeof(KKContext))]
    [Migration("20200115080324_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kelolakeuangan.Models.Account", b =>
                {
                    b.Property<int>("Id_Account")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_Family")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Account");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("kelolakeuangan.Models.Income", b =>
                {
                    b.Property<int>("Id_Income")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId_Account")
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Income");

                    b.HasIndex("AccountId_Account");

                    b.ToTable("Income");
                });

            modelBuilder.Entity("kelolakeuangan.Models.Spending", b =>
                {
                    b.Property<int>("Id_Spending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId_Account")
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Spending");

                    b.HasIndex("AccountId_Account");

                    b.ToTable("Spending");
                });

            modelBuilder.Entity("kelolakeuangan.Models.Wallet", b =>
                {
                    b.Property<int>("Id_Wallet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId_Account")
                        .HasColumnType("int");

                    b.Property<double>("Limit")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Wallet");

                    b.HasIndex("AccountId_Account");

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("kelolakeuangan.Models.Income", b =>
                {
                    b.HasOne("kelolakeuangan.Models.Account", null)
                        .WithMany("Incomes")
                        .HasForeignKey("AccountId_Account");
                });

            modelBuilder.Entity("kelolakeuangan.Models.Spending", b =>
                {
                    b.HasOne("kelolakeuangan.Models.Account", null)
                        .WithMany("Spendings")
                        .HasForeignKey("AccountId_Account");
                });

            modelBuilder.Entity("kelolakeuangan.Models.Wallet", b =>
                {
                    b.HasOne("kelolakeuangan.Models.Account", null)
                        .WithMany("Wallets")
                        .HasForeignKey("AccountId_Account");
                });
#pragma warning restore 612, 618
        }
    }
}
